version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  bot:
    build: ./bot
    container_name: bot
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./bot/.env
    depends_on:
      - backend

  # Optional: Reverse proxy for HTTPS + routing
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - bot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # for SSL certs
