"""coin payment

Revision ID: 16efaa9c7542
Revises: 8a9e739e4022
Create Date: 2025-10-17 14:26:41.396800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16efaa9c7542'
down_revision: Union[str, None] = '8a9e739e4022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinpayment', sa.Column('project_allocation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('coinpayment', sa.Column('reviewer_allocation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('coinpayment_assignment_id_fkey', 'coinpayment', type_='foreignkey')
    op.create_foreign_key(None, 'coinpayment', 'reviewerallocation', ['reviewer_allocation_id'], ['id'])
    op.create_foreign_key(None, 'coinpayment', 'agentallocation', ['project_allocation_id'], ['id'])
    op.drop_column('coinpayment', 'assignment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coinpayment', sa.Column('assignment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coinpayment', type_='foreignkey')
    op.drop_constraint(None, 'coinpayment', type_='foreignkey')
    op.create_foreign_key('coinpayment_assignment_id_fkey', 'coinpayment', 'agentallocation', ['assignment_id'], ['id'])
    op.drop_column('coinpayment', 'reviewer_allocation_id')
    op.drop_column('coinpayment', 'project_allocation_id')
    # ### end Alembic commands ###
