"""add reviewer_count default value

Revision ID: 21e0e8a18694
Revises: 93cd28c05f80
Create Date: 2025-10-14 07:49:33.683697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '21e0e8a18694'
down_revision: Union[str, None] = '93cd28c05f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('agent_quota', sa.INTEGER(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'agent_quota')
    # ### end Alembic commands ###
