"""add auto review column

Revision ID: 50695f812c39
Revises: 15935045efd7
Create Date: 2025-10-15 05:06:31.694051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50695f812c39'
down_revision: Union[str, None] = '15935045efd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('is_auto_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'is_auto_review')
    # ### end Alembic commands ###
