"""add reviewer_count default value

Revision ID: 93cd28c05f80
Revises: 033160c891fb
Create Date: 2025-10-14 07:46:33.125686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93cd28c05f80'
down_revision: Union[str, None] = '033160c891fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projectreviewer',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('added_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project', sa.Column('reviewer_quota', sa.INTEGER(), server_default='10', nullable=False))
    op.drop_column('project', 'per_user_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('per_user_quota', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('project', 'reviewer_quota')
    op.drop_table('projectreviewer')
    # ### end Alembic commands ###
