"""addedd instructions to table

Revision ID: a00259cf98d1
Revises: a7d89ed0872e
Create Date: 2025-10-09 07:48:22.958515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a00259cf98d1'
down_revision: Union[str, None] = 'a7d89ed0872e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('agent_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('reviewer_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('project', sa.Column('super_reviewer_instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'super_reviewer_instructions')
    op.drop_column('project', 'reviewer_instructions')
    op.drop_column('project', 'agent_instructions')
    # ### end Alembic commands ###
